Update page in Connect AWS Gateway “prepare-aws-api-gateway”
Axway/axway-open-docs pull request #1137
Opened 2020-09-08 22:18 UTC by jcollins-axway

Automatically generated by Netlify CMS

2020-09-08 22:36 UTC, jcollins-axway commented
@kflan-io @dfeldick @sbolosan @vivekschauhan - please review for content

2020-09-08 22:39 UTC, jcollins-axway commented
JIRA Tickets - APIGOV-15699 APIGOV-16040 APIGOV-15737

2020-09-08 22:40 UTC, sbolosan commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +* `cloudformation-synchronous-discovery.zip`: CloudFormation templates for operating in a synchronous discovery mode,
not sure what the ", " (comma) does here.  Is this a special mark down thingy?

2020-09-08 22:41 UTC, sbolosan commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +
are you trying to convey to create a resources directory inside of the bucket as well as a keys directory?  or a keys directory inside of the resources directory?

2020-09-08 22:41 UTC, kflan-io approved these changes

2020-09-08 22:43 UTC, sbolosan commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +
link to help create the SSH key?

2020-09-08 22:44 UTC, jcollins-axway commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +* `cloudformation-synchronous-discovery.zip`: CloudFormation templates for operating in a synchronous discovery mode,
good catch, will remove

2020-09-08 22:44 UTC, jcollins-axway commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +
yes I am <bucket>/resources/keys

2020-09-08 22:44 UTC, jcollins-axway commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +
good call

2020-09-08 22:50 UTC, jcollins-axway commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +
Within this bucket create a path of directories resources\keys:
?

2020-09-08 23:00 UTC, sbolosan commented on content/en/docs/central/connect-aws-gateway/prepare-aws-api-gateway.md
> +
yeah, i think that's better understood. To me anyways...

2020-09-08 23:11 UTC, sbolosan approved these changes

2020-09-09 00:05 UTC, cbordier approved these changes
I approve the changes.
@lbadenhop, please proceed.

2020-09-10 01:15 UTC, lbadenhop requested changes
Review "Create an EC2 SSH Key" changes

2020-09-10 14:31 UTC, lbadenhop approved these changes

2020-09-10 14:32 UTC, merged