Update page in AMPLIFY Unified Catalog “manage_subscriptions”
Axway/axway-open-docs pull request #1346
Opened 2020-10-26 22:35 UTC by jnamburi

Automatically generated by Netlify CMS

2020-10-29 14:56 UTC, andreamussap commented on content/en/docs/catalog/manage_subscriptions.md
> +description: This section describes how to manage your AMPLIFY Unified Catalog subscriptions
@jnamburi 'This section describes how' - not accepted because it's irrelevant, and we want to make the text shorter (as longer as is relevant), not longer.

2020-11-03 19:50 UTC, georgiana-caras requested changes

2020-11-03 19:50 UTC, georgiana-caras commented on content/en/docs/catalog/manage_subscriptions.md
> +![view subscriptions](/Images/catalog/view_subscriptions.gif "view subscriptions")
I cannot see the image. Is this the right link?

2020-11-03 19:50 UTC, georgiana-caras commented on content/en/docs/catalog/manage_subscriptions.md
> +### Enable manual subscriptions
Enable manual approvals

2020-11-03 19:50 UTC, georgiana-caras commented on content/en/docs/catalog/manage_subscriptions.md
> +![delete subscription](/Images/catalog/delete_subscription.gif "Delete subscription")
We need another section 
### Further information

-[Manage subscription workflow for V7 Manager](https://docs.axway.com/bundle/axway-open-docs/page/docs/central/connect-api-manager/subscription-for-the-consumer/index.html)
-[Manage subscription workflow for AWS](https://docs.axway.com/bundle/axway-open-docs/page/docs/central/connect-aws-gateway/subscription-for-the-consumer/index.html)

2020-11-03 20:19 UTC, jnamburi commented on content/en/docs/catalog/manage_subscriptions.md
> +### Enable manual subscriptions
updated!

2020-11-03 20:19 UTC, jnamburi commented on content/en/docs/catalog/manage_subscriptions.md
> +![view subscriptions](/Images/catalog/view_subscriptions.gif "view subscriptions")
you should see the images added here, I can view them on netlify - https://github.com/Axway/axway-open-docs/pull/1346/files

2020-11-03 20:58 UTC, jnamburi commented on content/en/docs/catalog/manage_subscriptions.md
> +![delete subscription](/Images/catalog/delete_subscription.gif "Delete subscription")
added the section.

2020-11-03 21:04 UTC, georgiana-caras approved these changes

2020-11-09 09:34 UTC, andreamussap approved these changes
https://deploy-preview-1346--axway-open-docs.netlify.app/docs/catalog/manage_subscriptions/

2020-11-09 09:35 UTC, merged