RDAPI-21835 doc(): update doc in yamles structure
Axway/axway-open-docs pull request #1505
Opened 2020-12-09 16:17 UTC by dominiquemongelli

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

2020-12-10 17:55 UTC, allandenis38 requested changes

2020-12-10 17:55 UTC, allandenis38 commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +The `types` folder is basically a directory tree on which relationships between types are managed in the logical manner of a directory tree.
@mcollins-axway Could you please help reword this part.

Proposal: The `types` directory contains subdirectories organized in a hierarchical tree structure that represents the inheritance relationships between types.

2020-12-10 17:55 UTC, allandenis38 commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +* In order to know what fields can be used, move up the types hierarchy.
Not sure to understand what "move up the types hierarchy." means.
Are we asking the user to look at the parent type higher in the types hierarchy to get the info ?

2020-12-10 17:55 UTC, allandenis38 commented on content/en/docs/apim_yamles/yamles_structure.md
> +The META-INF folder contains the `types` directory. This directory contains the definition of all the entity types in the entity store model. This it is where you can find useful information about th
"This it is where you can find useful..." => "This is where you can find useful.."

2020-12-10 18:00 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +The `types` folder is basically a directory tree on which relationships between types are managed in the logical manner of a directory tree.
I like your rewording @allandenis38

2020-12-11 09:01 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +The `types` folder is basically a directory tree on which relationships between types are managed in the logical manner of a directory tree.
Maybe use `META-INF/types` folder so its clear where to find it

2020-12-11 09:37 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +* As *NetService.yaml* file is containing within *JavaProcess* directory: `NetService` is a child type of `JavaProcess` type.
"is containing within" should be "is contained within"

2020-12-11 09:40 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +We could say that:
I wouldn't say "could", maybe "can" as its more definite.

2020-12-11 09:41 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +Custom types can be added by providing a yaml file definition of an entity type, and put in the right directory.
Custom types can be added by creating a YAML file definition of an entity type, and placing it in the correct subdirectory under `META-INF/types`.

2020-12-11 09:43 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +Looking at directory structure, *AnotherNetService.yaml* is containing inside *JavaProcess* directory. It means that `AnotherNetService` type is a child of `JavaProcess` type.
In the example directory structure above, `AnotherNetService.yaml` is contained inside the `JavaProcess` directory. This means that `AnotherNetService` type is a child type of the `JavaProcess` type.

2020-12-11 09:50 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +To create a `NetService` type
I'd remove line above as it sounds like we are adding a new type, but description below is about adding a new entity instance. replace with something like...

When you are creating new entity instance YAML files in your configuration use the content in the `META-INF/types` directory to discover the entity model definition so you know what fields the entity has, what type each field is, what cardinality each field has, and what default values apply. For example to create a new entity instance YAML file for a type `NetService`:

2020-12-11 10:20 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +* Identify under which directory the *NetService.yaml* file should be put in.
Totally confused by this as some of this text reads like you are adding a new "type" not a new "entity instance" which I think is what this section is about. I do think the original text was probably not 100% clear as it said "To create a NetService type" - I think it should have read "To create an instance of a NetService entity type" or similar.

2020-12-14 08:29 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +* Identify under which directory the *NetService.yaml* file should be put in.
Think I'll spit up the sections, 1 section about how to add a new type. Another one about adding a new instance. I'll reword

2020-12-14 10:58 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +* In order to know what fields can be used, move up the types hierarchy.
I have removed this section. It is not clear. I have added the infos on the dedicated section in "Custom types"

2020-12-14 10:59 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +* Identify under which directory the *NetService.yaml* file should be put in.
I have removed this section. Think it was not at the right place originally and agree it makes things confusting. All infos about custom types have been added in the dedicated section

2020-12-15 09:41 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +{{% /pageinfo %}}
Just small tweaks....
When adding a new custom entity type, the parent entity type of your custom type may not yet have any child entity types. In this case, create a new directory named the same as the parent type name (without `.yaml` extension) at the same level as the parent type YAML file. You can then put your new custom entity type YAML file in the newly created directory.

2020-12-15 09:42 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +Entity instances of custom types must be put in `System` directory. Refer to [Directory Mapping](/docs/apim_yamles/apim_yamles_references/yamles_top_directories) for more informations.
Maybe..

"YAML files for entity instances of custom.....

2020-12-15 09:43 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +Entity instances of custom types must be put in `System` directory. Refer to [Directory Mapping](/docs/apim_yamles/apim_yamles_references/yamles_top_directories) for more informations.
"for more informations" should be "for more information"

2020-12-15 10:03 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +{{% /pageinfo %}}
thanks!

2020-12-15 15:00 UTC, bordigoni commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +YAML files for entity instances of custom types must be put in `System` directory. Refer to [Directory Mapping](/docs/apim_yamles/apim_yamles_references/yamles_top_directories) for more information.
I theory It should be possible to set them in any directory as long as it does not contain a _parent.yaml. For instance a `Custom` directory could work.

2020-12-15 15:00 UTC, bordigoni commented on content/en/docs/apim_yamles/yamles_edit.md
> +* Search for YAML file `NetService.yaml` within `META-INF/types` directory
I know you probably just adapted something existing, but know with some experience, it is probably the worst scenario. I can contribute to fix that and take another example.

2020-12-15 15:04 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +YAML files for entity instances of custom types must be put in `System` directory. Refer to [Directory Mapping](/docs/apim_yamles/apim_yamles_references/yamles_top_directories) for more information.
Interesting. It should be validated and doc could be adapt accordingly

2020-12-15 15:05 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/yamles_edit.md
> +* Search for YAML file `NetService.yaml` within `META-INF/types` directory
Not sure to get what you mean. You are talking about this specific example NetService.yaml ?

2020-12-15 15:15 UTC, bordigoni commented on content/en/docs/apim_yamles/yamles_edit.md
> +* Search for YAML file `NetService.yaml` within `META-INF/types` directory
Yes. This is a corner case, not all subclass of ClassLoader and LoadableModule can fit a a component of NetService. It's been done this way because it can around 10 different cases. So high level classes have been used. I'll think of some example and do it as quickly as possible. Maybe something with a filter, everybody knows that and it is commonly used.

2020-12-16 12:30 UTC, andreamussap commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +YAML files for entity instances of custom types must be put in `System` directory. Refer to [Directory Mapping](/docs/apim_yamles/apim_yamles_references/yamles_top_directories) for more information.
I basically have today/tomorrow to finish this review. If you can't validate this between today/tomorrow, we can change the sentence to 'We recommend put the files in the system directory`, or 'You might add the files in any directory`... and then you create a Jira to test this, and update the doc accordingly ??

2020-12-16 12:32 UTC, andreamussap commented on content/en/docs/apim_yamles/yamles_edit.md
> +* Search for YAML file `NetService.yaml` within `META-INF/types` directory
_Ditto_. Depending on how you can test this, please create a Jira to update the doc later, just to avoid leaving this PR hanging until next year ??

2020-12-16 13:52 UTC, mcollins-axway commented on content/en/docs/apim_yamles/yamles_quick_start.md
> +If your are using git in Windows environment, make sure to activate git `longpaths` configuration to avoid *filename too long* error on checkout
If you are using git for your YAML configurations on a Windows operating system, make sure to set git configuration setting `core.longpaths` to avoid *filename too long* error on checkout.

2020-12-16 13:55 UTC, mcollins-axway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
> +When adding a new custom entity type, the parent entity type of your custom type may not yet have any child entity types. In this case, create a new directory named the same as the parent type name (
Missing full stop ?

2020-12-16 14:37 UTC, amussapvordel commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_top_directories.md
> +* Any other types (children of Root)
```suggestion
* Any other types (children of `root`)
```

2020-12-17 12:29 UTC, andreamussap commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
>  ## Cardinality
@dominiquemongelli this section needs an introductory sentence, otherwise the user won't know what this is about. "The following table shows ???"

2020-12-17 13:05 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_types.md
>  ## Cardinality
I take care of that

2020-12-17 15:09 UTC, andreamussap approved these changes

2020-12-17 15:11 UTC, merged