Update page in pol filter ref section “integrity_additional”
Axway/axway-open-docs pull request #1673
Opened 2021-03-01 13:06 UTC by ataparia-axway

Automatically generated by Netlify CMS

2021-03-01 13:20 UTC, ataparia-axway commented
@JuanAxway Please review!

2021-03-05 14:14 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +In Open Banking, the JSON Web Signature (JWS)can be detached. In that case the payload is omitted from the JWS and is sent separately. The detached JWS will be in the format `<header>..<signature>`.
I don't think we should mention Open Banking. Detached signatures can be used for other applications they are not specific to OB, but OB has a specific dependency on them. You could refer to Appendix F of RFC7515 https://tools.ietf.org/html/rfc7515#appendix-F

2021-03-05 14:24 UTC, JuanAxway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +In Open Banking, the JSON Web Signature (JWS)can be detached. In that case the payload is omitted from the JWS and is sent separately. The detached JWS will be in the format `<header>..<signature>`.
I agree with @JohnD-Axway, I think we should omit the "In Open Banking" part. I think a little intro is relevant, we could add a different text replacing the "In Open Banking" with:

A Detached Signature allows you to sign a content (body) of an HTTP request/response without its modification, the JSON Web Signature (JWS)can be detached. In that case, the payload is omitted from the JWS and is sent separately. The detached JWS will be in the format `<header>..<signature>`.  The `payload` missing from the JWS must be located on the Message via a Selector expression. This will typically be `${content.body}` as expected for Open Banking but is configurable in the filter.

2021-03-05 15:03 UTC, ataparia-axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +In Open Banking, the JSON Web Signature (JWS)can be detached. In that case the payload is omitted from the JWS and is sent separately. The detached JWS will be in the format `<header>..<signature>`.
Modified. Thanks!

2021-03-05 15:35 UTC, JohnD-Axway requested changes

2021-03-05 16:15 UTC, ataparia-axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +* When supporting detached signatures is enabled and at runtime, a token with a detached signature is processed and the filter can locate the detached payload at the location specified the filter pa
Rephrased it.

2021-03-05 16:16 UTC, ataparia-axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +
Added it as a note. Thanks John.

2021-03-05 16:28 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +
Thanks Ankit

2021-03-05 16:28 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +* When supporting detached signatures is enabled and at runtime, a token with a detached signature is processed and the filter can locate the detached payload at the location specified the filter pa
Thanks

2021-03-10 13:42 UTC, andreamussap commented
@ataparia-axway  @JohnD-Axway I've made some changes. Please let me know if the content is good to merge, or if I got something wrong, which needed to be updated. Thanks.

2021-03-10 13:55 UTC, ataparia-axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +The detached signature is disabled by default in the JWT Verify filter. To enable it, select **Support detached payload**, and specify the location of the payload in the `${content.body}`.
Hi @andreamussap, the location of the payload need not be in the ${content.body} every time, it can be anything. By default it is ${content.body} but can be changed.

If you can rephrase something like this:
"the location of the `payload` must be specified which is defaulted to `${content.body}`."

Thanks!

2021-03-10 14:20 UTC, andreamussap commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +The detached signature is disabled by default in the JWT Verify filter. To enable it, select **Support detached payload**, and specify the location of the payload in the `${content.body}`.
Done, thanks. Please check and let me know if you can spot any other detail to be updated, otherwise I'll merge the PR.

2021-03-10 14:27 UTC, ataparia-axway commented on content/en/docs/apim_policydev/apigw_polref/integrity_additional.md
> +The detached signature is disabled by default in the JWT Verify filter. To enable it, select **Support detached payload**, and specify the location of the payload in the `${content.body}`.
Looks good to me. Thanks!

2021-03-10 14:38 UTC, andreamussap approved these changes

2021-03-10 14:49 UTC, JohnD-Axway approved these changes

2021-03-10 14:51 UTC, merged