RDAPI-20494 Creation of new apigateway with yaml factory option
Axway/axway-open-docs pull request #1701
Opened 2021-03-12 17:05 UTC by dominiquemongelli

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-03-15 13:40 UTC, bordigoni commented on content/en/docs/apim_yamles/yamles_packaging_deployment.md
> +{{< alert title="Note">}}When a YAML configuration is deployed to an API Gateway group, it is still possible to switch it back and deploy an XML federated configuration to that same API Gateway group
```suggestion
{{< alert title="Note">}}When a YAML configuration is deployed to an API Gateway group, it is still possible to switch it back and deploy an XML federated configuration to that same API Gateway group. When an API Gateway instance is first created, an XML federated or YAML configuration is deployed with it.{{< /alert>}}
```

2021-03-17 17:25 UTC, allandenis38 approved these changes

2021-03-17 17:26 UTC, allandenis38 requested changes
Check if https://axway-open-docs.netlify.app/docs/apim_yamles/apim_yamles_references/yamles_known_limitations/ needs to be aligned

2021-03-18 08:24 UTC, dominiquemongelli commented
@allandenis38 I have removed the related section in known limitations

2021-03-18 08:33 UTC, allandenis38 approved these changes

2021-03-23 16:54 UTC, andreamussap approved these changes

2021-03-23 16:54 UTC, merged