Update page in APIM release note section “20210330_apimgr_relnotes”
Axway/axway-open-docs pull request #1708
Opened 2021-03-16 14:34 UTC by credmond-axway

Automatically generated by Netlify CMS

2021-03-16 15:03 UTC, credmond-axway commented
@JuanAxway @kmercierwhite

Please review.

Preview available here: https://deploy-preview-1708--axway-open-docs.netlify.app/docs/apim_relnotes/20210330_apimgr_relnotes/#fixed-security-vulnerabilities

2021-03-16 15:24 UTC, JuanAxway approved these changes

2021-03-16 15:28 UTC, mdenihan requested changes

2021-03-16 15:28 UTC, mdenihan commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +| RDAPI-23337 | | CVE-2018-1320 CVE-2019-0205 | **Issue**: Apache Cassandra includes libthrift library which has known vulnerabilities. **Resolution**: New installations which opt to install Cassandr
I'd just change the wording slightly;

> 0.9.3-1 library that addresses **these two** known vulnerabilities

2021-03-16 16:32 UTC, credmond-axway commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +| RDAPI-23337 | | CVE-2018-1320 CVE-2019-0205 | **Issue**: Apache Cassandra includes libthrift library which has known vulnerabilities. **Resolution**: New installations which opt to install Cassandr
Thanks @mdenihan. I've updated the wording.

2021-03-16 16:43 UTC, mdenihan approved these changes
Thanks @credmond-axway

2021-03-23 17:06 UTC, andreamussap commented
@cpalmeraxway Please attention to this PR so you don't overwrite the issue in this PR adding when you create your PR to add the list of fixed issues. Thanks.

2021-03-23 17:13 UTC, andreamussap approved these changes

2021-03-23 17:14 UTC, merged