Update page in pol filter ref section “utility_common”
Axway/axway-open-docs pull request #1711
Opened 2021-03-18 19:55 UTC by mvenzke-axway

Automatically generated by Netlify CMS

2021-03-19 10:19 UTC, maherb4 approved these changes

2021-03-19 22:23 UTC, mvenzke-axway commented
Related KBs:

https://support.axway.com/kb/177221/language/en
https://support.axway.com/kb/178780/language/en
https://support.axway.com/kb/177478/language/en

2021-03-25 14:12 UTC, andreamussap requested changes

2021-03-25 14:12 UTC, andreamussap commented on content/en/docs/apim_policydev/apigw_polref/utility_common.md
> +If this option is selected, the XML message is pretty-printed (indented) before it is output to the trace destination.
Test

2021-04-06 13:23 UTC, andreamussap approved these changes

2021-04-06 13:24 UTC, merged