Update page in APIG upgrade section “upgrade_steps_oneversion”
Axway/axway-open-docs pull request #1718
Opened 2021-03-22 10:46 UTC by markduig-ax

Automatically generated by Netlify CMS

2021-03-22 14:08 UTC, cgardineraxway commented
I have pinged @markduig-ax directly with some best practices when creating a PR. This PR is pending changes from @markduig-ax

2021-03-22 14:20 UTC, cgardineraxway requested changes

2021-03-22 14:20 UTC, cgardineraxway commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +When running the ./update_apigw.sh script users have the option of specifying a backup directory with specifying the  --backup_dir option.  This will create a copy of your existing installation direc
- change **with specifying the  --backup_dir option** to _by specifying the --backup_dir option_

2021-03-22 14:20 UTC, cgardineraxway commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +If there has a been significant changes to the configuration since the backup (for example changing the group configuration passphrase) you may not be to restore to a point where the external data wi
- **If there has a been significant changes** remove the a
- **you may not be to restore** change to _you may not be able to_

2021-03-22 14:20 UTC, cgardineraxway commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +Note: if you are updating to March2020 version or after you are recommended to run the kps re-encrypt script if you run this you will not be able to restore to a previous backup as some of the data w
- Remove the Note:

- **kps re-encrypt script if** full stop after script.
- **some of the data will not be able to read by the older configuration.** change to _some of the data will not be readable by the older configuration._

2021-03-22 14:21 UTC, cgardineraxway requested changes

2021-03-25 09:48 UTC, andreamussap commented
@markduig-ax I can't perform my review until you address and **close** the open comments. Thanks

2021-03-26 10:39 UTC, markduig-ax commented
Duplicate. Closing

2021-03-26 10:39 UTC, closed without merging