[RDAPI-21485] Adding section for automatic PS project upgrade
Axway/axway-open-docs pull request #1721
Opened 2021-03-22 16:38 UTC by Bcolemanaxway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Adding section for new feature that allows users to automatically upgrade old projects after upgrading Policy Studio to One Version.

Also adding same to March release notes.

## Deploy preview link

https://deploy-preview-1721--axway-open-docs.netlify.app/docs/apim_policydev/apigw_poldev/gs_project/
https://deploy-preview-1721--axway-open-docs.netlify.app/docs/apim_relnotes/20210330_apimgr_relnotes/

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [X] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-03-23 14:10 UTC, JohnD-Axway requested changes

2021-03-23 14:10 UTC, JohnD-Axway commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +Once a 7.7 One Version update is applied to Policy Studio, opening a pre-existing project will now offer to upgrade the project.
I don't think we use the term "One Version" in docs! It's an internal term.
Remove and just say Update

@andreamussap can you confirm?

2021-03-23 14:10 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_poldev/gs_project.md
> +After applying a One Version update to Policy Studio, it is not required to import old projects into the new Policy Studio. Instead, opening a project after the update will give the option of automat
"One Version" shouldn't be used (see below)

2021-03-23 14:16 UTC, andreamussap commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +Once a 7.7 One Version update is applied to Policy Studio, opening a pre-existing project will now offer to upgrade the project.
Yes, we use the term 'One Version' - https://axway-open-docs.netlify.app/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion/

2021-03-23 15:56 UTC, Bcolemanaxway commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +Once a 7.7 One Version update is applied to Policy Studio, opening a pre-existing project will now offer to upgrade the project.
I double checked as well because we had this question when I was making the One Version update doc itself, but the answer was that One Version is an external term also,
https://axway-open-docs.netlify.app/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion/

2021-03-23 16:18 UTC, JohnD-Axway commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +Once a 7.7 One Version update is applied to Policy Studio, opening a pre-existing project will now offer to upgrade the project.
Sorry - My mistake!
I was sure I had to remove it before.

2021-03-23 16:21 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_poldev/gs_project.md
> +After applying a One Version update to Policy Studio, it is not required to import old projects into the new Policy Studio. Instead, opening a project after the update will give the option of automat
Maybe remove "automatically"?
"option of automatically" sounds like an oxymoron.

2021-03-23 16:24 UTC, Bcolemanaxway commented on content/en/docs/apim_policydev/apigw_poldev/gs_project.md
> +After applying a One Version update to Policy Studio, it is not required to import old projects into the new Policy Studio. Instead, opening a project after the update will give the option of automat
Yeah you're right, think I was getting confused because I wasn't sure if it was automatic or if there was a dialog prompt or something.

2021-03-23 16:32 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_poldev/gs_project.md
> +After applying a One Version update to Policy Studio, it is not required to import old projects into the new Policy Studio. Instead, opening a project after the update will give the option of automat
We better confirm with Luis!

2021-03-23 16:44 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_poldev/gs_project.md
> +After applying a One Version update to Policy Studio, it is not required to import old projects into the new Policy Studio. Instead, opening a project after the update will give the option of automat
Confirmed - a dialog is presented so "automatically" should be removed.

2021-03-25 09:54 UTC, andreamussap commented on content/en/docs/apim_policydev/apigw_poldev/gs_project.md
> +After applying a One Version update to Policy Studio, it is not required to import old projects into the new Policy Studio. Instead, opening a project after the update will give the option of automat
@Bcolemanaxway did you address this comment? Can you click 'Resolve conversation' so I know this is ready for my review?

2021-03-25 13:56 UTC, andreamussap approved these changes

2021-03-25 13:57 UTC, andreamussap commented
@JohnD-Axway when you 'Request changes' you have to Approve the PR, otherwise merging is blocked.

2021-03-25 14:20 UTC, JohnD-Axway approved these changes

2021-03-25 14:24 UTC, merged