Rdapi 23024 fix yaml pk flaw revist doc for obsolete notions
Axway/axway-open-docs pull request #1722
Opened 2021-03-22 19:00 UTC by bordigoni

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-03-23 15:26 UTC, allandenis38 requested changes

2021-03-23 15:26 UTC, allandenis38 commented on content/en/docs/apim_yamles/yamles_structure.md
> +If you are using the `EntityStore` API, then all of that is handled internally and referring entities will be updated.
```suggestion
If you are using the `EntityStore` API, in case an entity's YamlPK is altered due to a change in any of its key fields, all referring entities are automatically updated to reflect the change.
 
```

2021-03-23 15:26 UTC, allandenis38 commented on content/en/docs/apim_yamles/yamles_structure.md
> +* `/Policies/App Policies/Core`: (container other policy)
(container other policy) => (container of other policies) or (contain other policies)

2021-03-23 15:26 UTC, allandenis38 commented on content/en/docs/apim_yamles/yamles_structure.md
> +In that case the YamlPK has is a little bit different.
```suggestion
In this case the YamlPK is formed differently to avoid ambiguity.
```

2021-03-23 15:26 UTC, allandenis38 commented on content/en/docs/apim_yamles/yamles_structure.md
> +There a conflict, YAML Entity store handle by setting their respective YamlPK to:
```suggestion
There is a conflict, the YAML Entity Store handles this by adding the parent container to the respective YamlPK:
```

2021-03-23 16:24 UTC, bordigoni commented on content/en/docs/apim_yamles/yamles_structure.md
> +There a conflict, YAML Entity store handle by setting their respective YamlPK to:
It's the type that we add but kept it as you suggested.

2021-03-25 12:07 UTC, andreamussap commented
Commit `1302557` *Merge branch 'developmar21' into RDAPI-23024-fix-yaml-pk-flaw-revist-* is to fix confict with https://github.com/Axway/axway-open-docs/pull/1701/files, where 'API Gateway group instance' was removed.

2021-03-25 12:11 UTC, andreamussap commented
@allandenis38 When you "Request a change" in a PR, I think you have to "Approve" the changes, otherwise merge will be blocked.

2021-03-25 13:26 UTC, allandenis38 commented
@andreamussap Sure I'll approve once all suggested changes are taken into consideration.

2021-03-25 13:32 UTC, andreamussap commented
> @andreamussap Sure I'll approve once all suggested changes are taken into consideration.

@allandenis38 but there's not open comments. This tells me that @bordigoni addressed all your comments??

2021-03-25 13:55 UTC, allandenis38 commented on content/en/docs/apim_yamles/yamles_structure.md
> +There a conflict, YAML Entity store handle by setting their respective YamlPK to:
Maybe this would be more accurate then ? => There is a conflict, the YAML Entity Store handles this by adding the types to the respective YamlPK:

2021-03-25 13:58 UTC, allandenis38 commented
@andreamussap Still one small adjustment to be more accurate might be required. I'll discussed it with Benoit and unblock the merge when ok for me. thx

2021-03-25 14:01 UTC, andreamussap commented
@allandenis38 No problem. I asked because all comments were close so I was about to start my review. Please you guys let me know when this is ready for me. Thanks

2021-03-25 14:10 UTC, allandenis38 commented on content/en/docs/apim_yamles/yamles_structure.md
> +There a conflict, YAML Entity store handle by setting their respective YamlPK to:
Already done

2021-03-25 14:10 UTC, allandenis38 approved these changes

2021-03-25 14:10 UTC, allandenis38 commented
@andreamussap We are good to go. thx

2021-03-26 09:15 UTC, andreamussap approved these changes

2021-03-26 09:16 UTC, merged