RDAPI-23679 - Updated March release notes with Common Criteria changes
Axway/axway-open-docs pull request #1729
Opened 2021-03-23 11:51 UTC by dmchughaxway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Updating the release notes to outline the Common criteria cipher and passphrase enforcement changes. 

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-03-23 15:16 UTC, clivequinn commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +The Key property store will not be re-encrypted. Therefore, to make use of the new more secure cipher scheme for the key property store data, run the run the KPS Admin Re-encrypt command. For more in
duplicate "run the"

2021-03-23 15:43 UTC, cgardineraxway requested changes

2021-03-23 15:43 UTC, cgardineraxway commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +The Key property store will not be re-encrypted. Therefore, to make use of the new more secure cipher scheme for the key property store data, run the run the KPS Admin Re-encrypt command. For more in
Could use a full stop here.

Also it is possible to specify the exact spot in the page we want the user to navigate to.

Can change this to /docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command/#re-encrypt-the-kps-data and it will take them to the Re-encrypt the KPS data section in the how_to_use_kpsadmin_command page.

2021-03-23 15:43 UTC, cgardineraxway commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +The entity store will be re-encrypted as part of the upgrade process. For more information, see [Upgrade Steps](/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion)
Could use a full stop at the end.

Also question, I don't see any mention of the entity store being re-encrypted in the Upgrade Steps link. Are we missing something there? The only mention I see is Apply modifications to Node Manager entity store configuration.

2021-03-25 07:14 UTC, cgardineraxway approved these changes

2021-03-25 16:41 UTC, andreamussap commented
@dmchughaxway as per our chat with @clivequinn please do some rewrite to the **Upgraded Cipher Scheme** section to remove detailed, specific information that fits in the documentation, having in mind that some customers will skip March 21 update, so the information in this page should be just an announcement about what's new, and then link to the pages of the docs where all customers, no matter which update they're coming and going they'll get the information.

Please double check with the experts where you should move the information to. If to https://axway-open-docs.netlify.app/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion/ ??

2021-03-25 16:42 UTC, andreamussap commented
Also, there's an update about this MK only in the mar21 branch for now. Please check if this is one link that you can use on your reference as well

 https://developmar21--axway-open-docs.netlify.app/docs/apimgmt_security/c_secgd_features_intro/#api-gateway-password-management-features

2021-03-25 16:54 UTC, andreamussap commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +A new passphrase policy and 2 new end-points to manage that passphrase policy were introduced in the January release.
This wasn't introduced in Jan21, but in Mar21, see https://github.com/Axway/axway-open-docs/pull/1639/files

So, it's ok to say that in this update we introduced 2 endpoints, and when the passphrase is enabled we enforce the policy, and that this allows for the user not to select weaker pwd, all great. But don't mention "**how**" you enable or disable the endpoints. 

For that you say, 'For more information, see [Configure a passphrase policy for node managers and API Gateway groups](/docs/apim_administration/apigtw_admin/manage_user_access/#configure-a-passphrase-policy-for-node-managers-and-api-gateway-groups)  ??

2021-03-26 14:59 UTC, dmchughaxway commented
@andreamussap, I have made the updates as discussed. Hopefully this all looks better. You can re-review now.

2021-03-26 15:32 UTC, andreamussap commented
Commit `4ce975a Merge branch 'developmar21' into RDAPI-23679` was to fix conflict with PR #1730

2021-03-26 17:09 UTC, andreamussap commented
> @andreamussap, I have made the updates as discussed. Hopefully this all looks better. You can re-review now.

@dmchughaxway Great work. This wasn't a trivial task!

Just FYI, feedback on the review:

* `/docs/apim_relnotes/20210330_apimgr_relnotes`: The new 'Cipher Scheme' section on the release notes is excellent.

* `/docs/apim_administration/apigtw_admin/manage_user_access`: Minor updates to improve the information.

* `/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md`: Removed section 'Updating to 7.7 March 2021...' because if they are upgrading directly to 'March 2021' they should read **at least** the correspondent Release Notes.

* `/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion`: I've made updates to the title and text to remove release-specific information, but I need someone to review my changes to make sure that I didn't get any terminology wrong.

2021-03-26 17:10 UTC, andreamussap commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +The cipher scheme is backwards compatible with [previous versions of the cipher scheme](/docs/apimgmt_security/compliance_appendix/), and it is able to decrypt data, which was encrypted in the old ci
I've added this link. Please check if this makes sense

2021-03-26 17:11 UTC, andreamussap commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +When instantiating a `PasswordCipher` in custom libraries or in Policy Studio script filters, be aware that this enhanced cipher algorithm might result in long generation times. While not recommended
"this enhanced cipher algorithm" - I've reworded this. Is it correct?

2021-03-26 17:12 UTC, andreamussap commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +To revert to an old version of the Cipher's algorithm, you can use the `setMode` method, such as in the following `jython` snippet:
"old version of the Cipher's algorithm" - I've reworded this. Is it correct?

2021-03-26 17:13 UTC, andreamussap commented
@matthewboss-axway and @mvenzke-axway This is a very important update. So, just tagging you FYI.

2021-03-29 10:53 UTC, clivequinn commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +When instantiating a `PasswordCipher` in custom libraries or in Policy Studio script filters, be aware that this enhanced cipher algorithm might result in long generation times. While not recommended
should it be "in a longer generation time"  ? 
Other than that looks good

2021-03-29 11:24 UTC, dmchughaxway commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +The cipher scheme is backwards compatible with [previous versions of the cipher scheme](/docs/apimgmt_security/compliance_appendix/), and it is able to decrypt data, which was encrypted in the old ci
I'm not sure if that is the correct link to be honest. I don't believe that it refers to the previous cipher scheme. However, I'd need @clivequinn to confirm. 

Also, I understand the heading change. However, I am not sure that it gets across to the customer that its a one shot thing i.e. do the re-encryption once and sort out your processes such that you ensure you are not moving data directly between environments with different domain ids. Perhaps again @clivequinn could review and provide an opinion

2021-03-29 11:26 UTC, dmchughaxway commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion.md
> +To revert to an old version of the Cipher's algorithm, you can use the `setMode` method, such as in the following `jython` snippet:
That rewording sounds fine to me.

2021-03-29 11:29 UTC, dmchughaxway commented
Hi @andreamussap, 

Just one last comment. You noted the following:

* /docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md: Removed section 'Updating to 7.7 March 2021...' because if they are upgrading directly to 'March 2021' they should read at least the correspondent Release Notes.

My understanding is that a customer can still use the upgrade script to upgrade to latest version (without using one version update). If this is the case, then it is probably important that there is a reference to the cipher changes that come into effect in March 2021. 

Again, I may have to leave this with @clivequinn to confirm. 

Thanks,

Deirdre

2021-03-29 13:10 UTC, clivequinn commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass.md
> -## Updating to 7.7 March 2021 Release (7.7.20210330) and beyond
Yes - i think we need to call this out. I don't thing we should remove it.

2021-03-29 13:37 UTC, andreamussap commented
Commit `7f8b305 Merge branch 'developmar21' into RDAPI-23679` is to fix conflict --> The branch is clean now, it has no conflicts with the base branch.

2021-03-29 15:36 UTC, clivequinn commented on content/en/docs/apim_relnotes/20210330_apimgr_relnotes.md
> +The cipher scheme for all encrypted data in the system (such as Database/LDAP passwords, Private keys, and son on) has been enhanced to use PBKDF2 (Password based key derivation function 2) with more
Typo - "and so on" - currently it says "and son on"

2021-03-29 16:45 UTC, andreamussap approved these changes

2021-03-29 16:47 UTC, merged