RDAPI-21747 - Update Embedded ActiveMQ Settings
Axway/axway-open-docs pull request #1829
Opened 2021-04-28 10:42 UTC by jolearyaxway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Update to the Embedded ActiveMQ Settings page to include information on the Enable Hostname Verification option.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-04-28 12:41 UTC, cgardineraxway requested changes

2021-04-28 12:41 UTC, cgardineraxway commented on content/en/docs/apim_reference/general_activemq_settings.md
> +The policy studio does not enable certificate creation with SANs, however certificates can be created elsewhere and imported using policy studio. For details on importing certificates, see [Manage X.
Can remove The from the beginning of the sentence. Also policy studio is usually capitalized in the documentation, so **Policy Studio**.

2021-04-28 13:02 UTC, cgardineraxway approved these changes

2021-04-29 10:26 UTC, andreamussap commented on content/en/docs/apim_reference/general_activemq_settings.md
> +Enables you to use certificates without any SANs, however doing so exposes a potential security risk.
'_exposes a potential security risk_' - This sentence seems a bit vague to me... @dmchughaxway @clivequinn  are you happy with this or is it possible to expand this 'alert' a little bit more?

2021-04-29 10:55 UTC, dmchughaxway commented
I cannot seem to respond to Andreas last comment. Anyway, I think yes it is a bit vague. The issue is that we probably don't want to invite someone to attempt a hack by being more explicit. Would something like the following be better?

Disabling hostname verification is a less secure option than a cert with the SANs and its only there for backwards compatibility if customers need it.

2021-04-29 10:55 UTC, dmchughaxway commented on content/en/docs/apim_reference/general_activemq_settings.md
> +Enables you to use certificates without any SANs, however doing so exposes a potential security risk.
I think yes it is a bit vague. The issue is that we probably don't want to invite someone to attempt a hack by being more explicit. Would something like the following be better?

Disabling hostname verification is a less secure option than a cert with the SANs and its only there for backwards compatibility if customers need it.

2021-04-29 11:03 UTC, dmchughaxway commented on content/en/docs/apim_reference/general_activemq_settings.md
> +Enables you to use certificates without any SANs, however doing so exposes a potential security risk.
@jolearyaxway @clivequinn what do you think?

2021-04-29 11:08 UTC, jolearyaxway commented on content/en/docs/apim_reference/general_activemq_settings.md
> +**Deactivating Hostname Verification**:
This to me makes it seem like its a separate option, when really you're just disabling the Enable Hostname Verification option.

2021-04-29 11:11 UTC, jolearyaxway commented on content/en/docs/apim_reference/general_activemq_settings.md
> +**Deactivating Hostname Verification**:
Maybe I can put this in a warning box?

2021-04-29 11:15 UTC, andreamussap commented on content/en/docs/apim_reference/general_activemq_settings.md
> +**Deactivating Hostname Verification**:
@jolearyaxway I've separated it because I thought that it was a separated option because they way you formatted it, in bold, when in fact, and just now I get it :), you should have formatted like 'Deactivating **Hostname Verification** (or, Deactivating this option) enables you to use certificates...'

So, please pull my changes to your branch, and update this together with the other bit. See Deirdre's comment above. Thanks.

2021-04-29 11:38 UTC, jolearyaxway commented on content/en/docs/apim_reference/general_activemq_settings.md
> +Enables you to use certificates without any SANs, however doing so exposes a potential security risk.
I think I'll drop the if customers need it part? sounds like we have become self aware.

2021-04-29 11:59 UTC, cgardineraxway requested changes

2021-04-29 11:59 UTC, cgardineraxway commented on content/en/docs/apim_reference/general_activemq_settings.md
> +Policy Studio does not enable certificate creation with SANs, but you can create certificates using 3rd party services or tools (like OpenSSL) and import them to Policy Studio. For details on importi
"and import them to Policy Studio." and import and deploy with Policy Studio.

2021-04-29 13:28 UTC, clivequinn commented
Looks good to me - well done @jolearyaxway

2021-04-29 13:55 UTC, cgardineraxway approved these changes

2021-04-29 15:24 UTC, merged