RDAPI-21747 Include ActiveMQ changes in release notes
Axway/axway-open-docs pull request #1850
Opened 2021-05-07 10:02 UTC by jolearyaxway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-05-07 11:41 UTC, dmchughaxway commented
I actually think the wording in the release notes should be a bit harder hitting. I just think branding it as a new feature makes it sound optional. Instead of:

_It is highly recommended to enable this feature, doing so will require a certificate update, please see [Embedded ActiveMQ settings in Policy Studio](/docs/apim_reference/general_activemq_settings/)_

Could we say:

Please review your Embedded Active MQ configuration. Enabling host name verification when using SSL is the more secure option and should be considered as part of the upgrade. Enabling host name verification requires a certificate update, please see [Embedded ActiveMQ settings in Policy Studio](/docs/apim_reference/general_activemq_settings/)

2021-05-07 13:40 UTC, cgardineraxway requested changes

2021-05-07 13:40 UTC, cgardineraxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +Hostname Verification can now be enabled on the Embedded ActiveMQ cluster, this is on by default on any new installs and will be off on upgrade to avoid breaking existing installs. Please review your
Hostname in the documentation is usually split into two words in the documentation. Host name. Apart from that. Everything is great.

2021-05-07 13:45 UTC, jolearyaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +Hostname Verification can now be enabled on the Embedded ActiveMQ cluster, this is on by default on any new installs and will be off on upgrade to avoid breaking existing installs. Please review your
Ah seems it's more popularly referred to as host name
https://english.stackexchange.com/a/100859

2021-05-07 14:08 UTC, cgardineraxway approved these changes

2021-05-07 14:15 UTC, dmchughaxway commented
Just one last (I hope) comment. Can we illustrate that we made the change due to an identified security vulnerability - CWE-933

2021-05-13 08:06 UTC, andreamussap commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +| Internal ID | Case ID            | Cve Identifier                               | Description      |
@cpalmeraxway Just FYI - Since you're the one who updates the fixe issues tables, just to let you know that Joel added an issue here.

2021-05-13 08:10 UTC, cpalmeraxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +| Internal ID | Case ID            | Cve Identifier                               | Description      |
Thanks!

2021-05-13 08:40 UTC, andreamussap commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +Host name verification was introduced to alleviate a potential CWE-933 security risk, and it is enabled by default on the Embedded ActiveMQ cluster of new API Gateway installations, which choose to u
@dmchughaxway I've made changes for Axway style and improve readability. Do you have any comments or can I merge the PR? Thanks

2021-05-13 09:12 UTC, dmchughaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +Host name verification is not enabled for upgrading customers, who use Embedded Active MQ with SSL enabled, because this causes their HMS queues to be unable to service requests. However, enabling ho
Small typos. Says HMS, should be JMS

2021-05-13 09:28 UTC, merged