RDAPI-24144 uprelease notes and pre may21 upgrade instructions
Axway/axway-open-docs pull request #1853
Opened 2021-05-07 15:46 UTC by benwaxway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

* Release note update
* Update in known limitations
* Instructions to allow upgrade pre May 21 YAML es

## Deploy preview link

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-05-10 15:44 UTC, dominiquemongelli commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +This work is an initiative born from collaborative customer hackathons to make the API Gateway configuration more CI/CD/DevOps and developer-friendly.​ It involved transforming the federated configur
There is no word about the new features included within the GA. I would say something that YamlES reached GA with the following additionnal features (upgrade...)

2021-05-10 15:44 UTC, dominiquemongelli commented on content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade.md
> +{{< alert title="Caution" color="warning" >}}
As we have much to say, I would add a dedicated section within the page instead of a "Caution" section.

2021-05-10 15:44 UTC, dominiquemongelli commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +For user who might already be using the technical preview since January 21 release please refer to [Upgrade YAML configuration](/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade) to enable upgrade
Should be part of the additional feature of the release

2021-05-11 07:26 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +This work is an initiative born from collaborative customer hackathons to make the API Gateway configuration more CI/CD/DevOps and developer-friendly.​ It involved transforming the federated configur
I'll let POs take a look at that. I don't know what to say for a release, I just copied some text from September release.

2021-05-11 07:27 UTC, benwaxway commented on content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade.md
> +{{< alert title="Caution" color="warning" >}}
I have been ask to add something in the release note

2021-05-11 07:36 UTC, benwaxway commented on content/en/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade.md
> +{{< alert title="Caution" color="warning" >}}
There is no existing, section. I don't know what title I should use ("Post May 21 upgrade", "Pre-May 21 upgrade " ?
@andreamussap what do you reckon we should do ?

2021-05-11 08:00 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +For user who might already be using the technical preview since January 21 release please refer to [Upgrade YAML configuration](/docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade) to enable upgrade
Not sure to get that

2021-05-12 16:28 UTC, allandenis38 requested changes

2021-05-12 16:28 UTC, allandenis38 commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
> +For user having configuration made with preview release since January 21 (prior versions are not supported) you must perform the following actions:
```suggestion
To upgrade your YAML configuration created from January 21 and March 21 releases you must perform the following actions:
```

2021-05-12 16:28 UTC, allandenis38 commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
> +For user having configuration made with preview release since January 21 (prior versions are not supported) you must perform the following actions:
I think we should add a separate note to clearly mention that upgrade of version prior to January 21 is not supported at all.

2021-05-12 16:28 UTC, allandenis38 commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +* Source code which is developer-friendly​.
Note sure to get the meaning

2021-05-12 16:28 UTC, allandenis38 commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +This work is an initiative born from collaborative customer hackathons to make the API Gateway configuration more CI/CD/DevOps and developer-friendly.​ It involved transforming the federated configur
The thing that we should highlight here is the fact that YAML-ES is now a GA feature and support upgrade and link to the new CLI capability /docs/apim_yamles/apim_yamles_cli/yamles_cli_upgrade

2021-05-17 09:35 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +* Source code which is developer-friendly​.
Change done for more clarity

2021-05-17 09:36 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +This work is an initiative born from collaborative customer hackathons to make the API Gateway configuration more CI/CD/DevOps and developer-friendly.​ It involved transforming the federated configur
Changed the RN to add this information

2021-05-17 09:37 UTC, allandenis38 approved these changes

2021-05-18 12:52 UTC, andreamussap commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +#### Update API Gateways with technical preview YAML configurations
@benwaxway If YAML configuration is GA from May 21, isn't it wrong to call this section 'technical preview', after all it's not tech preview **from** May anymore!?

2021-05-18 12:53 UTC, andreamussap commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +Perform these steps to update you installations:
(to update you installations) -> which installations? YAML configuration installations, or API Gateway installation?

2021-05-18 12:57 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +#### Update API Gateways with technical preview YAML configurations
This section is about telling how to update an API Gateway with a Jan21 or Mar21 YAML Configuration deployed -- which, BTW, is unlikely to happen and is not really supported, a huge number of manual step to do. As a user I may not want to do this but rather install a new version, or update my existing Prod Gatways that uses FED and then work with YAML now that is YAML. Long story short, I wouldn't pay too much attention on details on this for the reasons I mentioned.

2021-05-18 12:58 UTC, andreamussap commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +4. Perform [API Gateway server update](/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion/)
Asking the user to pause in the middle of a procedure, go to work on another procedure and then come back, in general doesn't work. Once the user goes to the Update one version procedure there's a high chance that they'll have trouble to find their way back here to step 5, and that's why I moved this instruction (Update your one version) to **before** this set of steps. 
So, can we stick with my previous change to provide a better UX?

2021-05-18 12:59 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +Perform these steps to update you installations:
API Gateway installation, sorry.

```suggestion
Perform these steps to update your API Gateway installations:
```
Beware, vocabulary is confusing
- Upgrade an API Gateway => from old versions to One Version
- Update an API Gateway => from One Version to a more recent One Version
- Upgrade a configuration (FED or YAML): migrate a configuration to the latest version

2021-05-18 12:59 UTC, andreamussap commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
> +* Technical preview releases ([API Gateway Jan 21](/docs/apim_relnotes/20210130_apimgr_relnotes/), [API Gateway Mar 21](/docs/apim_relnotes/20210330_apimgr_relnotes/)) can be upgraded with manual ste
As discussed and agreed with management, we have to avoid release-specific information in the one-version documentation, so I'm not accepting this change.

2021-05-18 13:00 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +#### Update API Gateways with technical preview YAML configurations
```suggestion
#### Update API Gateways with technical preview YAML configurations deployed
```

2021-05-18 13:01 UTC, andreamussap commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
> +To upgrade configurations made with **Preview releases** since [API Gateway Jan 21](/docs/apim_relnotes/20210130_apimgr_relnotes/) upgrade (prior versions are not supported), perform the following st
I don't know about the first occurrence o 'upgrade', but the second instance is '**update**'. FYI, API Gtw bimonthly releases are **updates**, not upgrades. So, I'll change the second one.

2021-05-18 13:03 UTC, benwaxway commented on content/en/docs/apim_relnotes/20210530_apimgr_relnotes.md
> +4. Perform [API Gateway server update](/docs/apim_installation/apigw_upgrade/upgrade_steps_oneversion/)
It won't work ;-) If users try to update their configuration with a YAML ES deployed on it it will fail.
But we could very well move section 5 before step 2, that would make more sense: back up and upgrade YAML config, then update Gateway, then deploy upgraded YAML Config.
What do think ?

2021-05-18 13:03 UTC, benwaxway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
> +* Technical preview releases ([API Gateway Jan 21](/docs/apim_relnotes/20210130_apimgr_relnotes/), [API Gateway Mar 21](/docs/apim_relnotes/20210330_apimgr_relnotes/)) can be upgraded with manual ste
Fair enough

2021-05-18 13:05 UTC, benwaxway commented on content/en/docs/apim_yamles/apim_yamles_references/yamles_known_limitations.md
> +To upgrade configurations made with **Preview releases** since [API Gateway Jan 21](/docs/apim_relnotes/20210130_apimgr_relnotes/) upgrade (prior versions are not supported), perform the following st
Agreed, but see my point above, upgrade configuration means "migrate configuration ta latest version". That is why the CLI command is named 'yamles upgrade"

2021-05-18 15:45 UTC, merged