[RDAPI-23220] Adding use of regular expression section to redaction
Axway/axway-open-docs pull request #1973
Opened 2021-07-02 12:38 UTC by scaro-axway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Add a redaction section to introduce the risks involved by using regular expressions.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-07-02 16:38 UTC, mvenzke-axway requested changes

2021-07-02 16:38 UTC, mvenzke-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +Some basic guidance rules to write efficient regular expressions could be:
```suggestion
To make your regular expressions more efficient, you should:
```

2021-07-02 16:38 UTC, mvenzke-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +The way regular expression patterns are written can result in performance drop and excessive use of resources (memory, stack size, CPU). An official PCRE ducomentation page is providing technical det
```suggestion
Inefficiently written regular expressions can result in poor performance and excessive use of resources such as memory, stack, and CPU.  The official [PCRE documentation page](https://www.pcre.org/original/doc/html/pcreperform.html) contains suggestions for how to make sure your regular expressions are written correctly.
```

2021-07-02 16:38 UTC, mvenzke-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +* Avoid using excessive recursion ([PCRE RECURSIVE PATTERNS](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC23)) and back references ([PCRE BACK REFERENCES](https://www.pcre.org/original/
```suggestion
* Avoid using [excessive recursion](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC23) and [back references](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC19) in your patterns as much as possible.
```

2021-07-02 16:38 UTC, mvenzke-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +* Use non-greedy patterns ([PCRE REPETITION](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC17)).
```suggestion
* Use [non-greedy patterns](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC17) when possible.
```

2021-07-02 16:38 UTC, mvenzke-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +* Avoid complexity: using different specific patterns for different needs is generally more efficient than using a single huge complex and generic expression.
```suggestion
* Use multiple regex patterns instead of one complex pattern.  Simple, specific patterns are more efficient than combining multiple patterns into a single expression with alternation.  Alternation may consume excessive stack memory.
```

2021-07-02 16:38 UTC, mvenzke-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +Use of PCRE recursive pattern is known to be able to cause stack overflows, which leads to process crash. On startup, API Gateway is evaluating the maximum recursion limit to use. That maximum recurs
```suggestion
Using recursive patterns may cause stack overflows, which has resulted in crashes. At startup, the API Gateway evaluates the maximum recursion limit to use, which defaults to 100. That maximum recursion limit is dynamically lowered whenever stack size is estimated to be dangerously low in order to prevent crashes.
```

2021-07-02 16:43 UTC, scaro-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +Use of PCRE recursive pattern is known to be able to cause stack overflows, which leads to process crash. On startup, API Gateway is evaluating the maximum recursion limit to use. That maximum recurs
There is no default value, this part is not to be included.

2021-07-02 17:02 UTC, mvenzke-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
> +Use of PCRE recursive pattern is known to be able to cause stack overflows, which leads to process crash. On startup, API Gateway is evaluating the maximum recursion limit to use. That maximum recurs
I thought the Jira claimed there was a limit of 100?  But if we don't want to discuss that it's fine.

2021-07-05 09:51 UTC, matthewboss-axway commented on content/en/docs/apim_administration/apigtw_admin/admin_redactors.md
>  * `multi`: Specifies whether the match is multi-line. In multi-line mode, `^` matches the beginning of line, and `$` matches the end of line. Defaults to `false`.
```suggestion
* `multi`: Specifies whether the match is multi-line. In multi-line mode, `^` and `$` match the beginning and end of any line within the redacted text. Defaults to `false`.
```

Minor change to correct what looks like a mistake. The original doesn't make any sense, does it?

2021-07-06 11:19 UTC, andreamussap approved these changes

2021-07-06 11:19 UTC, merged