Update 20211130_apip_relnotes.md
Axway/axway-open-docs pull request #2169
Opened 2021-11-29 14:39 UTC by dginevaAxway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

2021-11-30 16:58 UTC, jowens-axway requested changes
###Replacing Centos 8  as base OS
As Centos 8 is end of support in 2021, we are now providing API Portal in a docker container using the Alpine base OS instead. 

Also use "Elasticsearch" anywhere refer to Elastic, I believe that is the correct way to refer to to it.
Rest looks good!

2021-12-01 11:30 UTC, dginevaAxway commented
I add the changes and add a reference for elastic search configuration section.

2021-12-01 15:14 UTC, andreamussap commented on content/en/docs/apim_relnotes/20211130_apip_relnotes.md
> +### Centos 8 is replaced by Alpine
@dginevaAxway please have a look at my changes and let me know if it's ok to merge. Thanks

2021-12-01 17:12 UTC, merged

2021-12-02 11:23 UTC, dginevaAxway commented
@andreamussap Everything looks ok except the base operational system, BaseOS is a technical term and make scene for the people I wont replace it with similar words.

2021-12-02 11:24 UTC, dginevaAxway commented
@jowens-axway can you review this PR again for clarity if it's clear enough: (The publish/unpublish (enable/disable) toggle of Implicit flow will no longer affect)

2021-12-02 12:05 UTC, andreamussap commented
> BaseOS

@dginevaAxway ok, I will change it back. Just waiting for @jowens-axway feedback in case there's something else to change. 
John, I was talking to Dimi that the 'OAuth client credentials flow improvements' section doesn't seem clear to me, the part of the 'Implicit flow' without linking to a 'see more in documentation'. What do you think?

2021-12-02 21:37 UTC, jowens-axway commented
Am out of office but just a note on this - implicit flow being mentioned here is just complicating the message - we want to advertise that we now support client credentials flow inline with manager adding support.

I would tend to leave the message at that if possible.

From: Andrea ***@***.***>
Sent: 02 December 2021 12:06
To: Axway/axway-open-docs ***@***.***>
Cc: John Owens ***@***.***>; Mention ***@***.***>
Subject: Re: [Axway/axway-open-docs] IAP-4780 - Updates to API Portal release notes Nov 21 (PR #2169)


BaseOS

@dginevaAxway<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FdginevaAxway&data=04%7C01%7Cjowens%40axway.com%7C151c660a6cbd4e27b98f08d9b58c0d08%7C300f59df78e6436f9b27b64973e34f7d%7C1%7C0%7C637740435379123676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fYlh%2FRk%2Be1kir8h6UwmK%2Ff03A5kFfcnadArL2kkrdW4%3D&reserved=0> ok, I will change it back. Just waiting for @jowens-axway<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjowens-axway&data=04%7C01%7Cjowens%40axway.com%7C151c660a6cbd4e27b98f08d9b58c0d08%7C300f59df78e6436f9b27b64973e34f7d%7C1%7C0%7C637740435379123676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VOGTcCRGgKO005dQQthExp%2B%2FQT6QxrhgDgX53llXGJE%3D&reserved=0> feedback in case there's something else to change.
John, I was talking to Dimi that the 'OAuth client credentials flow improvements' section doesn't seem clear to me, the part of the 'Implicit flow' without linking to a 'see more in documentation'. What do you think?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAxway%2Faxway-open-docs%2Fpull%2F2169%23issuecomment-984566315&data=04%7C01%7Cjowens%40axway.com%7C151c660a6cbd4e27b98f08d9b58c0d08%7C300f59df78e6436f9b27b64973e34f7d%7C1%7C0%7C637740435379133633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nbUT8xDX%2FCrtjsILyVWUORFDFcTVAj%2Fmb8OvfdAY4is%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAM7C3WOM2V33ZR5PVXO6ZHDUO5OI7ANCNFSM5I7JNVDA&data=04%7C01%7Cjowens%40axway.com%7C151c660a6cbd4e27b98f08d9b58c0d08%7C300f59df78e6436f9b27b64973e34f7d%7C1%7C0%7C637740435379133633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SiRrEybvouFjhSTkU4L2u9Pbu3cgl7w2IXiO4KAcCZU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjowens%40axway.com%7C151c660a6cbd4e27b98f08d9b58c0d08%7C300f59df78e6436f9b27b64973e34f7d%7C1%7C0%7C637740435379143595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kfLB%2FlH47%2F%2FclE8RU65tEpotwtdbPTLUF93j5O7Srks%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjowens%40axway.com%7C151c660a6cbd4e27b98f08d9b58c0d08%7C300f59df78e6436f9b27b64973e34f7d%7C1%7C0%7C637740435379143595%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u0WllO0q310xCqC4mBQphOrLEabtSHZBKlgazB%2Bhnaw%3D&reserved=0>.