[RDAPI-26366] Document availability of YAML for EMT GW images
Axway/axway-open-docs pull request #2217
Opened 2022-02-08 14:48 UTC by drowe-axway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Using YAML configurations is now available when building and running gateway images/containers. This PR documents this change.

## Deploy preview link

To be added

## Checklist for contributors

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

2022-02-14 17:05 UTC, drowe-axway commented on content/en/docs/apim_installation/apigtw_install/system_requirements.md
> -ENV LANG=en_US.UTF-8
Should be resolved now.

2022-02-14 17:05 UTC, drowe-axway commented on content/en/docs/apim_installation/apigtw_install/system_requirements.md
> +LC_CTYPE=en_US.UTF-8
Same as below, should be ENV LANG=en_US.UTF-8

2022-02-16 10:24 UTC, kmercierwhite requested changes

2022-02-16 10:24 UTC, kmercierwhite commented on content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
> +* The `--yaml` option accepts `tar.gz`, `.tgz` or folder based YAML configurations.
The first extension here has no leading dot, but the second one does.

I think the --yaml option needs to be consistent here with what it accepts.

2022-02-16 15:58 UTC, drowe-axway commented on content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
> +* The `--yaml` option accepts `tar.gz`, `.tgz` or folder based YAML configurations.
You're right, will look at what other documents use and update it as appropriate

2022-02-16 16:17 UTC, drowe-axway commented on content/en/docs/apim_installation/apigw_containers/docker_script_gwimage.md
> +* The `--yaml` option accepts `tar.gz`, `.tgz` or folder based YAML configurations.
Done

2022-02-16 16:22 UTC, kmercierwhite approved these changes

2022-02-17 13:48 UTC, merged