[RDAPI-16377] Update OAuth flow pages to explain scope delimiters better
Axway/axway-open-docs pull request #2369
Opened 2022-07-12 10:57 UTC by drowe-axway

## Describe the changes

Update the OAuth flow pages so the scope delimiters outlined match the current Gateway functionality.
 
## Deploy preview link

tbd

## Checklist for contributors

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

2022-07-26 14:13 UTC, kmercierwhite requested changes

2022-07-26 14:13 UTC, kmercierwhite commented on content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_client_credentials.md
> +| `scope`      | Optional. The scope of the authorization. A comma (`,`) or a space ( ) are accepted as scope delimiters. Note that a plus (`+`) is NOT an accepted delimiter unless used to separate q
Double negative should be re-written to remove it. "**not** accepted **unless**" should be "also accepted when"

2022-07-26 14:13 UTC, kmercierwhite commented on content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_resource_owner.md
> +| `scope`      | Optional. The scope of the authorization. A comma (`,`) or a space ( ) are accepted as scope delimiters. Note that a plus (`+`) is NOT an accepted delimiter unless used to separate q
Same as written above, double negative (not & unless)

2022-07-26 14:13 UTC, kmercierwhite commented on content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_user_agent.md
> +| `scope`         | Optional. A space ( ) or comma (`,`) delimited list of scopes, which indicate the access to the resource owner's data requested by the application. A plus (`+`) is also accepted a
This is my favorite wording about the new change :)

2022-07-29 09:04 UTC, drowe-axway commented on content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_client_credentials.md
> +| `scope`      | Optional. The scope of the authorization. A comma (`,`) or a space ( ) are accepted as scope delimiters. Note that a plus (`+`) is NOT an accepted delimiter unless used to separate q
Changed!

2022-07-29 09:04 UTC, drowe-axway commented on content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_user_agent.md
> +| `scope`         | Optional. A space ( ) or comma (`,`) delimited list of scopes, which indicate the access to the resource owner's data requested by the application. A plus (`+`) is also accepted a
Changed!

2022-07-29 09:05 UTC, drowe-axway commented on content/en/docs/apim_policydev/apigw_oauth/oauth_flows/oauth_flows_resource_owner.md
> +| `scope`      | Optional. The scope of the authorization. A comma (`,`) or a space ( ) are accepted as scope delimiters. Note that a plus (`+`) is NOT an accepted delimiter unless used to separate q
Changed!

2022-07-29 15:16 UTC, drowe-axway reviewed
made changes

2022-08-02 09:27 UTC, merged