RDAPI-26820 - Cassandra 4 upgrade steps
Axway/axway-open-docs pull request #2523
Opened 2023-01-09 15:48 UTC by credmond-axway

## Describe the changes

Added a new page describing the Cassandra v4 upgrade procedure. Also moved the existing 3.x upgrade document to a new sub folder alongside the 4.x document

## Deploy preview link

http://pr-2523.axway-open-docs.opendocs-builder.pcloud.axway.int/docs/apim_installation/apigw_upgrade/upgrade_cassanda/

## Checklist for contributors

Before submitting this PR, please make sure:

_This is simply a reminder of what we are going to look for before merging your change._

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

2023-01-09 15:58 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 060ee00 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-2523.axway-open-docs.opendocs-builder.pcloud.axway.int |

2023-01-20 15:59 UTC, kmercierwhite requested changes

2023-01-20 15:59 UTC, kmercierwhite commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_cassanda/upgrade_cassandra_v4.md
> +* Download [Cassandra 4.0.7](https://support.axway.com/en/downloads/download-details/id/1452594) LINK TBC.
3 options here for now
1- direct link, https://archive.apache.org/dist/cassandra/4.0.7/
2- link to the cassandra site and ask them to search for the correct version. The link here would then be https://cassandra.apache.org/_/download.html
3- we host our own link (we did this for Cassandra 3.11, but ideally we should be encouraging the customer to get the link from the official site like we do for kubernetes or docker?)

2023-01-20 15:59 UTC, kmercierwhite commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_cassanda/upgrade_cassandra_v4.md
> +  "description": "Upgrade your Cassandra environment from version 3.11.11 to version 4.0.7 with no downtime."
We can't guarantee no downtime with a single node cluster, so I would remove that note here.

2023-01-20 15:59 UTC, kmercierwhite commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_cassanda/upgrade_cassandra_v4.md
> +   SELECT * from system.schema_keyspaces;
In Cassandra 3.11 it's

SELECT * from system_schema.keyspaces;

2023-01-20 15:59 UTC, kmercierwhite commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_cassanda/upgrade_cassandra_v4.md
> +Compare the configuration in `CASSANDRA_HOME/conf` of your current Cassandra installation to the configuration in the new Cassandra 4.0.7 installation, and apply any custom changes to the relevant co
Shouldn't this ask the user to compare their old config to a default config in 3.11.11, and then apply custom changes to the relevant config in 4.0.7? The current wording makes it sound like we're comparing the customer's old config to 4.0.7 directly.

2023-01-20 16:40 UTC, andreamussap commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_cassanda/upgrade_cassandra_v4.md
> +* Download [Cassandra 4.0.7](https://support.axway.com/en/downloads/download-details/id/1452594) LINK TBC.
Providing the direct link (option 1) provides a better UX. If we tell them to 'search' for the 'correct' version (option 2) there's always room for error; and agree with you in not providing a version hosted by Axway. So, let's go with option 1.

2023-01-20 16:41 UTC, kmercierwhite commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_cassanda/upgrade_cassandra_v4.md
> +* Download [Cassandra 4.0.7](https://support.axway.com/en/downloads/download-details/id/1452594) LINK TBC.
I'm happy with that decision.

2023-01-20 16:43 UTC, andreamussap commented on content/en/docs/apim_installation/apigw_upgrade/upgrade_cassanda/upgrade_cassandra_v4.md
> +Compare the configuration in `CASSANDRA_HOME/conf` of your current Cassandra installation to the configuration in the new Cassandra 4.0.7 installation, and apply any custom changes to the relevant co
@credmond-axway I wouldn't mind resolving Kelly's previous comments, but since this one is a technical feedback, which only you can resolve, then when you do it, please fix the others all together. Remember to pull my latest changes before applying new changes. Thanks!

2023-01-27 14:36 UTC, kmercierwhite approved these changes
Looks good now! Thanks Cian!

2023-01-27 16:53 UTC, merged