[RDAPI-29770] Updating default cipher string
Axway/axway-open-docs pull request #2629
Opened 2023-05-16 10:45 UTC by Bcolemanaxway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Updating default cipher string to align with what is shown in Policy Studio.

## Deploy preview link

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-05-16 10:47 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 7513e42 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-2629.axway-open-docs.opendocs-builder.pcloud.axway.int |

2023-05-18 09:47 UTC, JohnD-Axway requested changes

2023-05-18 09:47 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_external_connections/common_icap_conf.md
> +The default value is `FIPS:!SSLv3:!aNULL:!TLSv1:!kRSA`.
This isn't correct, the default value is still the old one.
Remove this update and we'll open a separate ticket to fix that.

2023-05-18 09:51 UTC, JohnD-Axway commented on content/en/docs/apim_policydev/apigw_external_connections/common_icap_conf.md
> +The default value is `FIPS:!SSLv3:!aNULL:!TLSv1:!kRSA`.
Ticket created: https://jira.axway.com/browse/RDAPI-29874

2023-05-18 09:57 UTC, Bcolemanaxway commented on content/en/docs/apim_policydev/apigw_external_connections/common_icap_conf.md
> +The default value is `FIPS:!SSLv3:!aNULL:!TLSv1:!kRSA`.
Reverted change to this file

2023-05-18 10:07 UTC, JohnD-Axway approved these changes

2023-05-19 11:19 UTC, merged