[RDAPI-29348] Update Aug23 release notes for Java 11 update
Axway/axway-open-docs pull request #2709
Opened 2023-08-25 12:34 UTC by JohnD-Axway

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-08-25 12:35 UTC, docsbuilder commented
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | 45bc386 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-2709.axway-open-docs.opendocs-builder.pcloud.axway.int |

2023-08-25 12:42 UTC, Bcolemanaxway commented on content/en/docs/apim_relnotes/20230830_apimgr_relnotes.md
> + - `javax.xml.bind package`: This package has been removed. If your code relies on JAXB for XML binding, you'll need to migrate to alternative libraries such as jakartat.xml.bind.
Typo on jakarta.xml.bind

2023-08-25 13:04 UTC, jolearyaxway commented
Is there a note elsewhere about the keystore passphrase required to match the key pass phrase or was that resolved in another way?
Is it worth noting the switch to PKCS12 by default now for new keystores?
Any note needed about jdbc11 ?

2023-08-25 13:09 UTC, jolearyaxway reviewed
Is there a note elsewhere about the keystore passphrase required to match the key pass phrase or was that resolved in another way?
Is it worth noting the switch to PKCS12 by default now for new keystores?
Any note needed about jdbc11 ?

2023-08-25 13:21 UTC, JohnD-Axway commented on content/en/docs/apim_relnotes/20230830_apimgr_relnotes.md
> + - `javax.xml.bind package`: This package has been removed. If your code relies on JAXB for XML binding, you'll need to migrate to alternative libraries such as jakartat.xml.bind.
good catch

2023-08-25 13:51 UTC, mbarova approved these changes

2023-08-25 14:14 UTC, Bcolemanaxway requested changes

2023-08-25 15:41 UTC, JohnD-Axway commented on content/en/docs/apim_relnotes/20230830_apimgr_relnotes.md
> + - `javax.xml.bind package`: This package has been removed. If your code relies on JAXB for XML binding, you'll need to migrate to alternative libraries such as jakartat.xml.bind.
This and other comments adressed!

2023-08-28 09:07 UTC, Bcolemanaxway approved these changes

2023-08-28 09:14 UTC, scaro-axway commented on content/en/docs/apim_relnotes/20230830_apimgr_relnotes.md
> + * Function changes: Some functions may have subtle changes to their output, this is not always covered by documentation. When tracking erroneous behavior all function outputs should be checked. For
It is '.getHostName()' that is replaced by '.getCanonicalHostName()', not the '.getHostAddress()'.

2023-08-28 09:38 UTC, andreamussap commented on content/en/docs/apim_relnotes/20230830_apimgr_relnotes.md
> + * Function changes: Some functions may have subtle changes to their output, this is not always covered by documentation. When tracking erroneous behavior all function outputs should be checked. For
Fixed, thanks!

2023-08-28 13:01 UTC, merged