[RDAPI-30769] GraphQL - Documentation
Axway/axway-open-docs pull request #2757
Opened 2023-11-16 15:29 UTC by lcattolico

Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

## Checklist for contributors

Before submitting this PR:

* Verify that all status checks have passed
* For more information on the Markdown linter rules, see [DavidAnson/markdownlint](https://github.com/DavidAnson/markdownlint)
* For first-time contributors, ensure that you have signed the [Axway CLA](https://cla.axway.com/)

2023-11-16 15:31 UTC, docsbuilder commented
### <span aria-hidden="true">âœ…</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">ðŸ”¨</span> Latest commit | ef70d0a2 |
 |<span aria-hidden="true">ðŸ˜Ž</span> Deploy preview | http://PR-2757.axway-open-docs.opendocs-builder.pcloud.axway.int |

2023-11-16 15:42 UTC, andreamussap commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +### GraphQL support
Support for GraphQL APIs

2023-11-16 15:47 UTC, lcattolico commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +### GraphQL support
Done

2023-11-21 14:37 UTC, jmbermingham approved these changes
Yep, looks good.

2023-11-21 15:07 UTC, dshielaxway requested changes

2023-11-21 15:07 UTC, dshielaxway commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +Now, from API Manager UI, you can import (register) a GraphQL back-end API by way of the API defition file, URL, or URL Introspection. Following, you can virtualize your registered back-end API as a
I think I'd rephrase the 2nd sentence slightly too. How about,

Subsequently, you can virtualize your registered back-end API exposing it as a publicly accessible front-end API, secure it and manage its API lifecycle.

2023-11-21 15:10 UTC, jmbermingham commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +Now, from API Manager UI, you can import (register) a GraphQL back-end API by way of the API defition file, URL, or URL Introspection. Following, you can virtualize your registered back-end API as a
That change looks fine, I think its better.

2023-11-21 15:22 UTC, andreamussap commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +Now, from API Manager UI, you can import (register) a GraphQL back-end API by way of the API defition file, URL, or URL Introspection. Following, you can virtualize your registered back-end API as a
@dshielaxway what about this one, do I keep it? Is "Alternatively" correct?

"Alternatively, API Manager allows you to proxy GraphQL APIs."

2023-11-21 15:30 UTC, dshielaxway commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +Now, from API Manager UI, you can import (register) a GraphQL back-end API by way of the API defition file, URL, or URL Introspection. Following, you can virtualize your registered back-end API as a
Sorry, I didn't answer the question.

I'd leave it as 'Subsequently, ...'

2023-11-21 15:41 UTC, andreamussap commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +This update of API Gateway ships with support for GraphQL APIs. This enables customers to import GraphQL specifications, virtualize the registered back-end API exposing it as a publicly accessible fr
@dshielaxway I had to make some change in order to use your suggestion. There was no need to use "subsequently" after that. Please let me know if the text is ok. Thanks.

2023-11-21 15:44 UTC, dshielaxway commented on content/en/docs/apim_relnotes/20231130_apimgr_relnotes.md
> +This update of API Gateway ships with support for GraphQL APIs. This enables customers to import GraphQL specifications, virtualize the registered back-end API exposing it as a publicly accessible fr
Yeah, that reads better. Thanks!

2023-11-22 10:06 UTC, merged